# Travis config for Synthesis
language: c

cache:
  directories:
    - nim-devel
    - nim-stable

matrix:
  include:
    # Weave only works with Nim devel
    # Build and test using both gcc and clang
    # Build and test on both x86-64 and ARM64
    - os: linux
      env: CHANNEL=devel
      compiler: gcc

    - os: linux
      arch: arm64
      env: CHANNEL=devel
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: clang

    # On OSX we only test against clang (gcc is mapped to clang by default)
    - os: osx
      env: CHANNEL=devel
      compiler: clang
  fast_finish: true

before_install:
  - |
    if [ "${CHANNEL}" = stable ]; then
      BRANCH="v$(curl https://nim-lang.org/channels/stable)"
    else
      BRANCH="${CHANNEL}"
    fi

install:
  # Detect caching of Nim compiler
  - |
    if [ ! -x "nim-${CHANNEL}/bin/nim" ]; then
      git clone -b "${BRANCH}" https://github.com/nim-lang/nim "nim-${CHANNEL}/"
      pushd "nim-${CHANNEL}"
      git clone --depth 1 https://github.com/nim-lang/csources csources/
      pushd csources
      sh build.sh
      popd
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
      ./koch tools
    else
      pushd "nim-${CHANNEL}"
      git fetch origin "${BRANCH}"
      if ! git merge FETCH_HEAD | grep "Already up.to.date"; then
        bin/nim c koch
        ./koch boot -d:release
        ./koch tools
      fi
    fi
    popd
before_script:
    - export PATH="nim-${CHANNEL}/bin${PATH:+:$PATH}"
script:
    - nimble refresh
    - nimble test
branches:
  except:
    - gh-pages
